dist: trusty

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
 # - "pypy"  # PyPy2 2.5.0
 # - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

addons:
  sonarqube:
    branches:
      - develop

install:
  - pip install .
  - pip install codecov
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=sandman setup.py test
  - sonar-scanner

after_success:
  - codecov
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
