language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - pytest
  - sonar-scanner

after_sucess:
  - codeclimate-test-reporter
