#!/bin/sh 

### BEGIN INIT INFO
# Provides:          server-sleep
# Required-Start:    $syslog $local_fs $network $remote_fs
# Required-Stop:     $syslog $local_fs $network $remote_fs
# Should-Start:      $remote_fs $named
# Should-Stop:       $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts server-sleep daemon
# Description:       This script runs the server-sleep service
### END INIT INFO
#
### CONFIGURATION
PATH="/opt/server-sleep"			# Path to server-sleep
PYTHON="/usr/bin/python"			# Path to python installation
LOG="/var/log/server-sleep.log"		# Path to Logfile
PID="/var/run/server-sleep.pid"		# Path to ProcessID-file
#################
 
start() {
 echo "Starting Service: server-sleep"
 start-stop-daemon --start --oknodo --pidfile ${PID} --background --chdir ${PATH} --startas ${PYTHON} server-sleep.py -- >>${LOG} 2>>${LOG}
}
 
stop() {
 echo "Stopping Service: server-sleep"
 start-stop-daemon --stop --oknodo --pidfile ${PID} --retry=TERM/30/KILL/5
}
 
case "$1" in
 start)
 start
 ;;
 stop)
 stop
 ;;
 restart)
 stop
 sleep 4
 start
 ;;
 *)
 echo "Usage: $0 (start|stop|restart)"
 exit 1
 ;;
esac
 
exit 0